//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.19 at 05:48:41 PM IST 
//


package com.soap.api.students.dto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.api.students.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.api.students.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteStudentByIdRequest }
     * 
     */
    public DeleteStudentByIdRequest createDeleteStudentByIdRequest() {
        return new DeleteStudentByIdRequest();
    }

    /**
     * Create an instance of {@link GetStudentByIdResponse }
     * 
     */
    public GetStudentByIdResponse createGetStudentByIdResponse() {
        return new GetStudentByIdResponse();
    }

    /**
     * Create an instance of {@link StudentInfo }
     * 
     */
    public StudentInfo createStudentInfo() {
        return new StudentInfo();
    }

    /**
     * Create an instance of {@link StudentDetailsResponse }
     * 
     */
    public StudentDetailsResponse createStudentDetailsResponse() {
        return new StudentDetailsResponse();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link DeleteStudentByIdResponse }
     * 
     */
    public DeleteStudentByIdResponse createDeleteStudentByIdResponse() {
        return new DeleteStudentByIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link StudentDetailsRequest }
     * 
     */
    public StudentDetailsRequest createStudentDetailsRequest() {
        return new StudentDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentByIdRequest }
     * 
     */
    public UpdateStudentByIdRequest createUpdateStudentByIdRequest() {
        return new UpdateStudentByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentByIdResponse }
     * 
     */
    public UpdateStudentByIdResponse createUpdateStudentByIdResponse() {
        return new UpdateStudentByIdResponse();
    }

    /**
     * Create an instance of {@link GetStudentByIdRequest }
     * 
     */
    public GetStudentByIdRequest createGetStudentByIdRequest() {
        return new GetStudentByIdRequest();
    }

}
